import 'package:flutter/material.dart';
import 'package:flutterapp/floiveryapp/generatedhomewidget/generated/GeneratedStatusBarWidget4.dart';
import 'package:flutterapp/floiveryapp/generatedhomewidget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/floiveryapp/generatedhomewidget/generated/GeneratedToplogoWidget.dart';
import 'package:flutterapp/floiveryapp/generatedhomewidget/generated/GeneratedPopularchoicesWidget.dart';
import 'package:flutterapp/floiveryapp/generatedhomewidget/generated/GeneratedLocationbarWidget.dart';
import 'package:flutterapp/floiveryapp/generatedhomewidget/generated/GeneratedPromotionCardWidget.dart';
import 'package:flutterapp/floiveryapp/generatedhomewidget/generated/GeneratedCategorysectionWidget.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 390.0,
              height: 865.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 24.0,
                      top: 126.0,
                      right: null,
                      bottom: null,
                      width: 347.0,
                      height: 37.0,
                      child: GeneratedLocationbarWidget(),
                    ),
                    Positioned(
                      left: 29.0,
                      top: 185.0,
                      right: null,
                      bottom: null,
                      width: 348.0,
                      height: 177.0,
                      child: GeneratedCategorysectionWidget(),
                    ),
                    Positioned(
                      left: 29.0,
                      top: 732.0,
                      right: null,
                      bottom: null,
                      width: 142.0,
                      height: 38.0,
                      child: GeneratedPopularchoicesWidget(),
                    ),
                    Positioned(
                      left: 28.0,
                      top: 369.0,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 356.0,
                      child: GeneratedPromotionCardWidget(),
                    ),
                    Positioned(
                      left: 33.0,
                      top: 55.0,
                      right: null,
                      bottom: null,
                      width: 323.0,
                      height: 50.0,
                      child: GeneratedToplogoWidget(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 768.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 76.0,
              child: GeneratedGroup7Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 43.0,
              child: GeneratedStatusBarWidget4(),
            )
          ]),
    ));
  }
}
