import 'package:flutter/material.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderreadywidget/generated/GeneratedLine3Widget2.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderreadywidget/generated/GeneratedIconWidget89.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderreadywidget/generated/GeneratedStatusBarWidget13.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderreadywidget/generated/GeneratedIconOutlineiconuserremoveWidget.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderreadywidget/generated/GeneratedIconOutlinecogWidget.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderreadywidget/generated/GeneratedIconOutlinephoneWidget.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderreadywidget/generated/GeneratedGroup36Widget.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderreadywidget/generated/GeneratedLoginbuttonWidget2.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderreadywidget/generated/GeneratedIconOutlinehomeWidget.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderreadywidget/generated/GeneratedIconOutlinecurrencydollarWidget17.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderreadywidget/generated/GeneratedCONFIRMORDERWidget.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderreadywidget/generated/GeneratedGroup35Widget.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderreadywidget/generated/GeneratedLine9Widget.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderreadywidget/generated/GeneratedSignupbuttonWidget6.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderreadywidget/generated/GeneratedIconOutlinecreditcardWidget.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderreadywidget/generated/GeneratedGroup34Widget1.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderreadywidget/generated/GeneratedToplogoWidget9.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderreadywidget/generated/GeneratedGroup8Widget21.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderreadywidget/generated/GeneratedIconWidget88.dart';

/* Frame Confirm-order-ready
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedConfirmorderreadyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 390.0,
              height: 841.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 33.0,
                      top: 57.0,
                      right: null,
                      bottom: null,
                      width: 323.0,
                      height: 50.0,
                      child: GeneratedToplogoWidget9(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 765.0,
                      right: null,
                      bottom: null,
                      width: 390.0,
                      height: 76.0,
                      child: GeneratedGroup8Widget21(),
                    ),
                    Positioned(
                      left: 112.0,
                      top: 101.0,
                      right: null,
                      bottom: null,
                      width: 166.0,
                      height: 42.0,
                      child: GeneratedCONFIRMORDERWidget(),
                    ),
                    Positioned(
                      left: 104.0,
                      top: 141.0,
                      right: null,
                      bottom: null,
                      width: 186.0,
                      height: 1.0,
                      child: GeneratedLine3Widget2(),
                    ),
                    Positioned(
                      left: 42.0,
                      top: 585.0,
                      right: null,
                      bottom: null,
                      width: 315.0,
                      height: 48.0,
                      child: GeneratedSignupbuttonWidget6(),
                    ),
                    Positioned(
                      left: 48.0,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 220.0,
                      height: 416.0,
                      child: TransformHelper.translate(
                          x: 0.00,
                          y: -57.50,
                          z: 0,
                          child: GeneratedLoginbuttonWidget2()),
                    ),
                    Positioned(
                      left: 201.0,
                      top: 374.0,
                      right: null,
                      bottom: null,
                      width: 163.0,
                      height: 33.0,
                      child: GeneratedGroup34Widget1(),
                    ),
                    Positioned(
                      left: 185.0,
                      top: 426.0,
                      right: null,
                      bottom: null,
                      width: 182.03408813476562,
                      height: 32.0,
                      child: GeneratedGroup35Widget(),
                    ),
                    Positioned(
                      left: 135.0,
                      top: 474.0,
                      right: null,
                      bottom: null,
                      width: 243.0,
                      height: 32.0,
                      child: GeneratedGroup36Widget(),
                    ),
                    Positioned(
                      left: 211.0,
                      top: 337.0,
                      right: null,
                      bottom: null,
                      width: 12.0,
                      height: 3.5,
                      child: GeneratedLine9Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.04358974358974359;

                        final double height =
                            constraints.maxHeight * 0.020214030915576695;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.06153846153846154,
                              y: constraints.maxHeight * 0.4530321046373365,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child:
                                    GeneratedIconOutlineiconuserremoveWidget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.041025641025641026;

                        final double height =
                            constraints.maxHeight * 0.019024970273483946;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.06153846153846154,
                              y: constraints.maxHeight * 0.5160523186682521,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedIconOutlinephoneWidget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 26.0,
                      top: 537.0,
                      right: null,
                      bottom: null,
                      width: 15.0,
                      height: 15.0,
                      child: GeneratedIconOutlinecurrencydollarWidget17(),
                    ),
                    Positioned(
                      left: 20.0,
                      top: 482.0,
                      right: null,
                      bottom: null,
                      width: 24.0,
                      height: 24.0,
                      child: GeneratedIconOutlinehomeWidget(),
                    ),
                    Positioned(
                      left: 20.0,
                      top: 326.0,
                      right: null,
                      bottom: null,
                      width: 24.0,
                      height: 24.0,
                      child: GeneratedIconOutlinecreditcardWidget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.06153846153846154;

                        final double height =
                            constraints.maxHeight * 0.028537455410225922;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.05384615384615385,
                              y: constraints.maxHeight * 0.3281807372175981,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedIconOutlinecogWidget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.03333333333333333;
                        double scaleX =
                            (constraints.maxWidth * percentWidth) / 13.0;

                        double percentHeight = 0.015457788347205707;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) / 13.0;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.0641025641025641,
                              translateY:
                                  constraints.maxHeight * 0.2080856123662307,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedIconWidget88())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.03076923076923077;
                        double scaleX =
                            (constraints.maxWidth * percentWidth) / 12.0;

                        double percentHeight = 0.0178359096313912;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) / 15.0;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.06666666666666667,
                              translateY:
                                  constraints.maxHeight * 0.267538644470868,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedIconWidget89())
                        ]);
                      }),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 43.0,
              child: GeneratedStatusBarWidget13(),
            )
          ]),
    ));
  }
}
