import 'package:flutter/material.dart';
import 'package:flutterapp/floiveryapp/generatedstoreslistwidget/generated/GeneratedGroup28Widget.dart';
import 'package:flutterapp/floiveryapp/generatedstoreslistwidget/generated/GeneratedGroup38Widget.dart';
import 'package:flutterapp/floiveryapp/generatedstoreslistwidget/generated/GeneratedStatusBarWidget7.dart';
import 'package:flutterapp/floiveryapp/generatedstoreslistwidget/generated/GeneratedGroup7Widget2.dart';
import 'package:flutterapp/floiveryapp/generatedstoreslistwidget/generated/GeneratedGroup20Widget1.dart';
import 'package:flutterapp/floiveryapp/generatedstoreslistwidget/generated/GeneratedToplogoWidget4.dart';
import 'package:flutterapp/floiveryapp/generatedstoreslistwidget/generated/GeneratedGroup27Widget.dart';
import 'package:flutterapp/floiveryapp/generatedstoreslistwidget/generated/GeneratedToplogoWidget3.dart';
import 'package:flutterapp/floiveryapp/generatedstoreslistwidget/generated/GeneratedGroup29Widget.dart';
import 'package:flutterapp/floiveryapp/generatedstoreslistwidget/generated/GeneratedGroup39Widget.dart';
import 'package:flutterapp/floiveryapp/generatedstoreslistwidget/generated/GeneratedStatusBarWidget8.dart';
import 'package:flutterapp/floiveryapp/generatedstoreslistwidget/generated/GeneratedGroup26Widget.dart';

/* Frame Stores-list
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStoreslistWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 390.0,
              height: 844.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 49.0,
                      top: 127.5,
                      right: null,
                      bottom: null,
                      width: 111.0,
                      height: 32.0,
                      child: GeneratedGroup39Widget(),
                    ),
                    Positioned(
                      left: 33.0,
                      top: 57.0,
                      right: null,
                      bottom: null,
                      width: 323.0,
                      height: 50.0,
                      child: GeneratedToplogoWidget3(),
                    ),
                    Positioned(
                      left: 49.0,
                      top: 127.5,
                      right: null,
                      bottom: null,
                      width: 140.0,
                      height: 32.0,
                      child: GeneratedGroup38Widget(),
                    ),
                    Positioned(
                      left: 33.0,
                      top: 57.0,
                      right: null,
                      bottom: null,
                      width: 323.0,
                      height: 50.0,
                      child: GeneratedToplogoWidget4(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 176.0,
                      right: null,
                      bottom: null,
                      width: 390.0,
                      height: 120.0,
                      child: GeneratedGroup26Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 307.0,
                      right: null,
                      bottom: null,
                      width: 390.0,
                      height: 120.0,
                      child: GeneratedGroup27Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 572.0,
                      right: null,
                      bottom: null,
                      width: 390.0,
                      height: 120.0,
                      child: GeneratedGroup28Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 438.0,
                      right: null,
                      bottom: null,
                      width: 390.0,
                      height: 120.0,
                      child: GeneratedGroup29Widget(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 768.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 76.0,
              child: GeneratedGroup7Widget2(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 43.0,
              child: GeneratedStatusBarWidget7(),
            ),
            Positioned(
              left: 0.0,
              top: 767.9999389648438,
              right: null,
              bottom: null,
              width: 390.0,
              height: 76.00006103515625,
              child: GeneratedGroup20Widget1(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 43.0,
              child: GeneratedStatusBarWidget8(),
            )
          ]),
    ));
  }
}
