import 'package:flutter/material.dart';
import 'package:flutterapp/floiveryapp/generatedsearchmorewidget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/floiveryapp/generatedsearchmorewidget/generated/GeneratedSignupbuttonWidget5.dart';
import 'package:flutterapp/floiveryapp/generatedsearchmorewidget/generated/GeneratedIconOutlinecurrencydollarWidget16.dart';
import 'package:flutterapp/floiveryapp/generatedsearchmorewidget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/floiveryapp/generatedsearchmorewidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/floiveryapp/generatedsearchmorewidget/generated/GeneratedPricerangeWidget18.dart';
import 'package:flutterapp/floiveryapp/generatedsearchmorewidget/generated/GeneratedLine2Widget18.dart';
import 'package:flutterapp/floiveryapp/generatedsearchmorewidget/generated/GeneratedFlowersourceWidget18.dart';
import 'package:flutterapp/floiveryapp/generatedsearchmorewidget/generated/GeneratedStatusBarWidget11.dart';
import 'package:flutterapp/floiveryapp/generatedsearchmorewidget/generated/GeneratedSittellus6qtWidget.dart';
import 'package:flutterapp/floiveryapp/generatedsearchmorewidget/generated/Generated13Widget.dart';
import 'package:flutterapp/floiveryapp/generatedsearchmorewidget/generated/GeneratedGroup7Widget4.dart';
import 'package:flutterapp/floiveryapp/generatedsearchmorewidget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/floiveryapp/generatedsearchmorewidget/generated/GeneratedToplogoWidget7.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/floiveryapp/generatedsearchmorewidget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/floiveryapp/generatedsearchmorewidget/generated/GeneratedFeugiataccumsan4qtWidget.dart';
import 'package:flutterapp/floiveryapp/generatedsearchmorewidget/generated/GeneratedStandartsize30\$Widget.dart';
import 'package:flutterapp/floiveryapp/generatedsearchmorewidget/generated/GeneratedPINKROSESBOUQUETWidget.dart';
import 'package:flutterapp/floiveryapp/generatedsearchmorewidget/generated/GeneratedChoosebouquetsizeWidget.dart';
import 'package:flutterapp/floiveryapp/generatedsearchmorewidget/generated/GeneratedFlowersusedWidget.dart';
import 'package:flutterapp/floiveryapp/generatedsearchmorewidget/generated/GeneratedSedenim3qtWidget.dart';
import 'package:flutterapp/floiveryapp/generatedsearchmorewidget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitEgetinte.dart';

/* Frame Search-more
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchmoreWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1072.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 390.0,
                            height: 1072.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 33.0,
                                    top: 57.0,
                                    right: null,
                                    bottom: null,
                                    width: 323.0,
                                    height: 50.0,
                                    child: GeneratedToplogoWidget7(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 121.0,
                                    right: null,
                                    bottom: null,
                                    width: 390.0,
                                    height: 369.0,
                                    child: GeneratedRectangle7Widget(),
                                  ),
                                  Positioned(
                                    left: 137.0,
                                    top: 457.0,
                                    right: null,
                                    bottom: null,
                                    width: 18.0,
                                    height: 18.0,
                                    child:
                                        GeneratedIconOutlinecurrencydollarWidget16(),
                                  ),
                                  Positioned(
                                    left: 33.0,
                                    top: 411.0,
                                    right: null,
                                    bottom: null,
                                    width: 256.0,
                                    height: 50.0,
                                    child: GeneratedPINKROSESBOUQUETWidget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.19230769230769232;

                                      final double height =
                                          constraints.maxHeight *
                                              0.033175283403538945;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.08461538461538462,
                                            y: constraints.maxHeight *
                                                0.41697761194029853,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child:
                                                  GeneratedFlowersourceWidget18(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.15128205128205127;

                                      final double height =
                                          constraints.maxHeight *
                                              0.024253731343283583;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.4025641025641026,
                                            y: constraints.maxHeight *
                                                0.4216417910447761,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child:
                                                  GeneratedPricerangeWidget18(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 349.0,
                                    top: 135.0,
                                    right: null,
                                    bottom: null,
                                    width: 25.0,
                                    height: 33.0,
                                    child: Generated13Widget(),
                                  ),
                                  Positioned(
                                    left: 45.0,
                                    top: 506.0,
                                    right: null,
                                    bottom: null,
                                    width: 316.0,
                                    height: 226.0,
                                    child:
                                        GeneratedLoremipsumdolorsitametconsecteturadipiscingelitEgetinte(),
                                  ),
                                  Positioned(
                                    left: 45.0,
                                    top: 797.0,
                                    right: null,
                                    bottom: null,
                                    width: 107.0,
                                    height: 34.0,
                                    child: GeneratedFlowersusedWidget(),
                                  ),
                                  Positioned(
                                    left: 37.0,
                                    top: 938.0,
                                    right: null,
                                    bottom: null,
                                    width: 315.0,
                                    height: 48.0,
                                    child: GeneratedSignupbuttonWidget5(),
                                  ),
                                  Positioned(
                                    left: 45.0,
                                    top: 841.0,
                                    right: null,
                                    bottom: null,
                                    width: 11.0,
                                    height: 11.0,
                                    child: GeneratedEllipse1Widget(),
                                  ),
                                  Positioned(
                                    left: 72.0,
                                    top: 831.0,
                                    right: null,
                                    bottom: null,
                                    width: 117.0,
                                    height: 34.0,
                                    child: GeneratedSittellus6qtWidget(),
                                  ),
                                  Positioned(
                                    left: 44.0,
                                    top: 730.0,
                                    right: null,
                                    bottom: null,
                                    width: 123.0,
                                    height: 34.0,
                                    child: GeneratedChoosebouquetsizeWidget(),
                                  ),
                                  Positioned(
                                    left: 45.0,
                                    top: 906.0,
                                    right: null,
                                    bottom: null,
                                    width: 11.0,
                                    height: 11.0,
                                    child: GeneratedEllipse3Widget(),
                                  ),
                                  Positioned(
                                    left: 72.0,
                                    top: 896.0,
                                    right: null,
                                    bottom: null,
                                    width: 119.0,
                                    height: 34.0,
                                    child: GeneratedSedenim3qtWidget(),
                                  ),
                                  Positioned(
                                    left: 45.0,
                                    top: 874.0,
                                    right: null,
                                    bottom: null,
                                    width: 11.0,
                                    height: 11.0,
                                    child: GeneratedEllipse2Widget(),
                                  ),
                                  Positioned(
                                    left: 72.0,
                                    top: 864.0,
                                    right: null,
                                    bottom: null,
                                    width: 188.0,
                                    height: 34.0,
                                    child: GeneratedFeugiataccumsan4qtWidget(),
                                  ),
                                  Positioned(
                                    left: 44.0,
                                    top: 762.0,
                                    right: null,
                                    bottom: null,
                                    width: 305.0,
                                    height: 33.0,
                                    child: GeneratedRectangle8Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      double percentWidth =
                                          0.014418458938598633;
                                      double scaleX = (constraints.maxWidth *
                                              percentWidth) /
                                          5.623198986053467;

                                      double percentHeight =
                                          0.0071032572148451165;
                                      double scaleY = (constraints.maxHeight *
                                              percentHeight) /
                                          7.614691734313965;

                                      return Stack(children: [
                                        TransformHelper.translateAndScale(
                                            translateX: constraints.maxWidth *
                                                0.16809520232371794,
                                            translateY: constraints.maxHeight *
                                                0.7246946647985658,
                                            translateZ: 0,
                                            scaleX: scaleX,
                                            scaleY: scaleY,
                                            scaleZ: 1,
                                            child: GeneratedLine2Widget18())
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 70.0,
                                    top: 762.0,
                                    right: null,
                                    bottom: null,
                                    width: 146.0,
                                    height: 34.0,
                                    child: GeneratedStandartsize30$Widget(),
                                  ),
                                  Positioned(
                                    left: -1.0,
                                    top: 771.0,
                                    right: null,
                                    bottom: null,
                                    width: 390.0,
                                    height: 76.0,
                                    child: GeneratedGroup7Widget4(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 43.0,
              child: GeneratedStatusBarWidget11(),
            )
          ]),
    ));
  }
}
