import 'package:flutter/material.dart';
import 'package:flutterapp/floiveryapp/generatedprofilewidget/generated/GeneratedGroup37Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/floiveryapp/generatedprofilewidget/generated/GeneratedToplogoWidget11.dart';
import 'package:flutterapp/floiveryapp/generatedprofilewidget/generated/GeneratedEllipse4Widget.dart';
import 'package:flutterapp/floiveryapp/generatedprofilewidget/generated/GeneratedGroup8Widget23.dart';
import 'package:flutterapp/floiveryapp/generatedprofilewidget/generated/GeneratedStatusBarWidget15.dart';
import 'package:flutterapp/floiveryapp/generatedprofilewidget/generated/GeneratedIconWidget100.dart';

/* Frame Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 390.0,
              height: 841.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 33.0,
                      top: 57.0,
                      right: null,
                      bottom: null,
                      width: 323.0,
                      height: 50.0,
                      child: GeneratedToplogoWidget11(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 765.0,
                      right: null,
                      bottom: null,
                      width: 390.0,
                      height: 76.0,
                      child: GeneratedGroup8Widget23(),
                    ),
                    Positioned(
                      left: 24.0,
                      top: 256.0,
                      right: null,
                      bottom: null,
                      width: 315.0,
                      height: 360.0,
                      child: GeneratedGroup37Widget(),
                    ),
                    Positioned(
                      left: 138.0,
                      top: 121.0,
                      right: null,
                      bottom: null,
                      width: 105.0,
                      height: 105.0,
                      child: GeneratedEllipse4Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.04893434475629758;
                        double scaleX = (constraints.maxWidth * percentWidth) /
                            19.084394454956055;

                        double percentHeight = 0.02140309155766944;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) / 18.0;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.7615384615384615,
                              translateY:
                                  constraints.maxHeight * 0.5743162901307967,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedIconWidget100())
                        ]);
                      }),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 43.0,
              child: GeneratedStatusBarWidget15(),
            )
          ]),
    ));
  }
}
