import 'package:flutter/material.dart';
import 'package:flutterapp/floiveryapp/generatedloginpagewidget/generated/GeneratedLoginbuttonWidget1.dart';
import 'package:flutterapp/floiveryapp/generatedloginpagewidget/generated/GeneratedGroup6Widget1.dart';
import 'package:flutterapp/floiveryapp/generatedloginpagewidget/generated/GeneratedStatusBarWidget2.dart';
import 'package:flutterapp/floiveryapp/generatedloginpagewidget/generated/GeneratedGroup2Widget1.dart';
import 'package:flutterapp/floiveryapp/generatedloginpagewidget/generated/GeneratedLogoWidget2.dart';
import 'package:flutterapp/floiveryapp/generatedloginpagewidget/generated/GeneratedSignupbuttonWidget2.dart';

/* Frame Log in page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginpageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 390.0,
              height: 844.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 249, 249, 249),
                      ),
                    ),
                    Positioned(
                      left: 90.0,
                      top: 70.0,
                      right: null,
                      bottom: null,
                      width: 210.0,
                      height: 216.0,
                      child: GeneratedLogoWidget2(),
                    ),
                    Positioned(
                      left: 41.0,
                      top: 581.0,
                      right: null,
                      bottom: null,
                      width: 312.0,
                      height: 49.0,
                      child: GeneratedSignupbuttonWidget2(),
                    ),
                    Positioned(
                      left: 39.0,
                      top: 382.0,
                      right: null,
                      bottom: null,
                      width: 314.0,
                      height: 64.0,
                      child: GeneratedGroup6Widget1(),
                    ),
                    Positioned(
                      left: 39.0,
                      top: 473.0,
                      right: null,
                      bottom: null,
                      width: 314.0,
                      height: 64.0,
                      child: GeneratedGroup2Widget1(),
                    ),
                    Positioned(
                      left: 39.0,
                      top: 650.0,
                      right: null,
                      bottom: null,
                      width: 314.0,
                      height: 48.0,
                      child: GeneratedLoginbuttonWidget1(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 43.0,
              child: GeneratedStatusBarWidget2(),
            )
          ]),
    ));
  }
}
