import 'package:flutter/material.dart';
import 'package:flutterapp/floiveryapp/generatedrecoverpassword1widget/generated/GeneratedGroup6Widget2.dart';
import 'package:flutterapp/floiveryapp/generatedrecoverpassword1widget/generated/GeneratedSignupbuttonWidget3.dart';
import 'package:flutterapp/floiveryapp/generatedrecoverpassword1widget/generated/GeneratedLogoWidget3.dart';
import 'package:flutterapp/floiveryapp/generatedrecoverpassword1widget/generated/GeneratedStatusBarWidget3.dart';

/* Frame Recover password-1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRecoverpassword1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 390.0,
              height: 844.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 249, 249, 249),
                      ),
                    ),
                    Positioned(
                      left: 90.0,
                      top: 70.0,
                      right: null,
                      bottom: null,
                      width: 210.0,
                      height: 216.0,
                      child: GeneratedLogoWidget3(),
                    ),
                    Positioned(
                      left: 41.0,
                      top: 487.0,
                      right: null,
                      bottom: null,
                      width: 312.0,
                      height: 49.0,
                      child: GeneratedSignupbuttonWidget3(),
                    ),
                    Positioned(
                      left: 39.0,
                      top: 382.0,
                      right: null,
                      bottom: null,
                      width: 314.0,
                      height: 64.0,
                      child: GeneratedGroup6Widget2(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 43.0,
              child: GeneratedStatusBarWidget3(),
            )
          ]),
    ));
  }
}
