import 'package:flutter/material.dart';
import 'package:flutterapp/floiveryapp/generatedsignuppagewidget/generated/GeneratedStatusBarWidget1.dart';
import 'package:flutterapp/floiveryapp/generatedsignuppagewidget/generated/GeneratedLogoWidget1.dart';
import 'package:flutterapp/floiveryapp/generatedsignuppagewidget/generated/GeneratedFrame1Widget.dart';

/* Frame Sign UP page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignUPpageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 390.0,
              height: 844.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 249, 249, 249),
                      ),
                    ),
                    Positioned(
                      left: 90.0,
                      top: 70.0,
                      right: null,
                      bottom: null,
                      width: 210.0,
                      height: 216.0,
                      child: GeneratedLogoWidget1(),
                    )
                  ]),
            ),
            Positioned(
              left: 39.0,
              top: 311.0,
              right: null,
              bottom: null,
              width: 315.0,
              height: 470.0,
              child: GeneratedFrame1Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 43.0,
              child: GeneratedStatusBarWidget1(),
            )
          ]),
    ));
  }
}
