import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/floiveryapp/generatedspecificsearchwidget/generated/GeneratedLocationbarWidget2.dart';
import 'package:flutterapp/floiveryapp/generatedspecificsearchwidget/generated/GeneratedToplogoWidget1.dart';
import 'package:flutterapp/floiveryapp/generatedspecificsearchwidget/generated/GeneratedGroup19Widget.dart';
import 'package:flutterapp/floiveryapp/generatedspecificsearchwidget/generated/GeneratedGroup20Widget.dart';
import 'package:flutterapp/floiveryapp/generatedspecificsearchwidget/generated/GeneratedStatusBarWidget6.dart';
import 'package:flutterapp/floiveryapp/generatedspecificsearchwidget/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/floiveryapp/generatedspecificsearchwidget/generated/GeneratedLocationbarWidget1.dart';
import 'package:flutterapp/floiveryapp/generatedspecificsearchwidget/generated/GeneratedGroup17Widget.dart';
import 'package:flutterapp/floiveryapp/generatedspecificsearchwidget/generated/GeneratedGroup15Widget.dart';
import 'package:flutterapp/floiveryapp/generatedspecificsearchwidget/generated/GeneratedToplogoWidget2.dart';
import 'package:flutterapp/floiveryapp/generatedspecificsearchwidget/generated/GeneratedGroup14Widget.dart';
import 'package:flutterapp/floiveryapp/generatedspecificsearchwidget/generated/GeneratedGroup16Widget.dart';
import 'package:flutterapp/floiveryapp/generatedspecificsearchwidget/generated/GeneratedGroup12Widget.dart';
import 'package:flutterapp/floiveryapp/generatedspecificsearchwidget/generated/GeneratedGroup7Widget1.dart';
import 'package:flutterapp/floiveryapp/generatedspecificsearchwidget/generated/GeneratedGroup11Widget.dart';
import 'package:flutterapp/floiveryapp/generatedspecificsearchwidget/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/floiveryapp/generatedspecificsearchwidget/generated/GeneratedStatusBarWidget5.dart';
import 'package:flutterapp/floiveryapp/generatedspecificsearchwidget/generated/GeneratedGroup13Widget.dart';
import 'package:flutterapp/floiveryapp/generatedspecificsearchwidget/generated/GeneratedIconWidget28.dart';

/* Frame Specific-search
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSpecificsearchWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 930.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 390.0,
                            height: 930.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 33.0,
                                    top: 125.0,
                                    right: null,
                                    bottom: null,
                                    width: 341.0,
                                    height: 37.0,
                                    child: GeneratedLocationbarWidget1(),
                                  ),
                                  Positioned(
                                    left: 33.0,
                                    top: 57.0,
                                    right: null,
                                    bottom: null,
                                    width: 323.0,
                                    height: 50.0,
                                    child: GeneratedToplogoWidget1(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 180.0,
                                    right: null,
                                    bottom: null,
                                    width: 390.0,
                                    height: 120.0,
                                    child: GeneratedGroup10Widget(),
                                  ),
                                  Positioned(
                                    left: -1.0,
                                    top: 438.0,
                                    right: null,
                                    bottom: null,
                                    width: 390.0,
                                    height: 120.0,
                                    child: GeneratedGroup12Widget(),
                                  ),
                                  Positioned(
                                    left: -1.0,
                                    top: 309.0,
                                    right: null,
                                    bottom: null,
                                    width: 390.0,
                                    height: 120.0,
                                    child: GeneratedGroup11Widget(),
                                  ),
                                  Positioned(
                                    left: -1.0,
                                    top: 572.0,
                                    right: null,
                                    bottom: null,
                                    width: 390.0,
                                    height: 120.0,
                                    child: GeneratedGroup13Widget(),
                                  ),
                                  Positioned(
                                    left: -1.0,
                                    top: 708.0,
                                    right: null,
                                    bottom: null,
                                    width: 390.0,
                                    height: 120.0,
                                    child: GeneratedGroup14Widget(),
                                  ),
                                  Positioned(
                                    left: 33.0,
                                    top: 125.0,
                                    right: null,
                                    bottom: null,
                                    width: 341.0,
                                    height: 37.0,
                                    child: GeneratedLocationbarWidget2(),
                                  ),
                                  Positioned(
                                    left: 33.0,
                                    top: 57.0,
                                    right: null,
                                    bottom: null,
                                    width: 323.0,
                                    height: 50.0,
                                    child: GeneratedToplogoWidget2(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 180.0,
                                    right: null,
                                    bottom: null,
                                    width: 390.0,
                                    height: 120.0,
                                    child: GeneratedGroup15Widget(),
                                  ),
                                  Positioned(
                                    left: -1.0,
                                    top: 438.0,
                                    right: null,
                                    bottom: null,
                                    width: 391.0,
                                    height: 120.0,
                                    child: GeneratedGroup16Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 309.0,
                                    right: null,
                                    bottom: null,
                                    width: 390.0,
                                    height: 120.0,
                                    child: GeneratedGroup17Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      double percentWidth = 0.03461538461538462;
                                      double scaleX = (constraints.maxWidth *
                                              percentWidth) /
                                          13.5;

                                      double percentHeight =
                                          0.014516129032258065;
                                      double scaleY = (constraints.maxHeight *
                                              percentHeight) /
                                          13.5;

                                      return Stack(children: [
                                        TransformHelper.translateAndScale(
                                            translateX: constraints.maxWidth *
                                                0.7051282051282052,
                                            translateY: constraints.maxHeight *
                                                0.3774193548387097,
                                            translateZ: 0,
                                            scaleX: scaleX,
                                            scaleY: scaleY,
                                            scaleZ: 1,
                                            child: GeneratedIconWidget28())
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: -1.0,
                                    top: 572.0,
                                    right: null,
                                    bottom: null,
                                    width: 393.0,
                                    height: 120.0,
                                    child: GeneratedGroup18Widget(),
                                  ),
                                  Positioned(
                                    left: -1.0,
                                    top: 708.0,
                                    right: null,
                                    bottom: null,
                                    width: 391.0,
                                    height: 120.0,
                                    child: GeneratedGroup19Widget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 768.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 76.0,
              child: GeneratedGroup7Widget1(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 43.0,
              child: GeneratedStatusBarWidget5(),
            ),
            Positioned(
              left: 0.0,
              top: 768.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 76.0,
              child: GeneratedGroup20Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 43.0,
              child: GeneratedStatusBarWidget6(),
            )
          ]),
    ));
  }
}
