import 'package:flutter/material.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderpickedwidget/generated/GeneratedIconOutlineiconuserremoveWidget1.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderpickedwidget/generated/GeneratedGroup35Widget1.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderpickedwidget/generated/GeneratedStatusBarWidget14.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderpickedwidget/generated/GeneratedIconWidget97.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderpickedwidget/generated/GeneratedIconOutlinehomeWidget1.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderpickedwidget/generated/GeneratedLoginWidget3.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderpickedwidget/generated/GeneratedIconWidget98.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderpickedwidget/generated/GeneratedGroup8Widget22.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderpickedwidget/generated/GeneratedLine3Widget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderpickedwidget/generated/GeneratedIconOutlinecurrencydollarWidget18.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderpickedwidget/generated/GeneratedSignupbuttonWidget7.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderpickedwidget/generated/GeneratedLine9Widget1.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderpickedwidget/generated/GeneratedToplogoWidget10.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderpickedwidget/generated/GeneratedIconOutlinecogWidget1.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderpickedwidget/generated/GeneratedCONFIRMORDERWidget1.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderpickedwidget/generated/GeneratedGroup36Widget1.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderpickedwidget/generated/GeneratedGroup34Widget2.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderpickedwidget/generated/GeneratedIconOutlinephoneWidget1.dart';
import 'package:flutterapp/floiveryapp/generatedconfirmorderpickedwidget/generated/GeneratedIconOutlinecreditcardWidget1.dart';

/* Frame Confirm-order-picked
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedConfirmorderpickedWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 390.0,
              height: 841.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 33.0,
                      top: 57.0,
                      right: null,
                      bottom: null,
                      width: 323.0,
                      height: 50.0,
                      child: GeneratedToplogoWidget10(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 765.0,
                      right: null,
                      bottom: null,
                      width: 390.0,
                      height: 76.0,
                      child: GeneratedGroup8Widget22(),
                    ),
                    Positioned(
                      left: 112.0,
                      top: 101.0,
                      right: null,
                      bottom: null,
                      width: 166.0,
                      height: 42.0,
                      child: GeneratedCONFIRMORDERWidget1(),
                    ),
                    Positioned(
                      left: 104.0,
                      top: 141.0,
                      right: null,
                      bottom: null,
                      width: 186.0,
                      height: 1.0,
                      child: GeneratedLine3Widget3(),
                    ),
                    Positioned(
                      left: 42.0,
                      top: 585.0,
                      right: null,
                      bottom: null,
                      width: 315.0,
                      height: 48.0,
                      child: GeneratedSignupbuttonWidget7(),
                    ),
                    Positioned(
                      left: 203.0,
                      top: 398.0,
                      right: null,
                      bottom: null,
                      width: 163.0,
                      height: 33.0,
                      child: GeneratedGroup34Widget2(),
                    ),
                    Positioned(
                      left: 184.0,
                      top: 447.0,
                      right: null,
                      bottom: null,
                      width: 182.03408813476562,
                      height: 32.0,
                      child: GeneratedGroup35Widget1(),
                    ),
                    Positioned(
                      left: 138.0,
                      top: 495.0,
                      right: null,
                      bottom: null,
                      width: 243.0,
                      height: 32.0,
                      child: GeneratedGroup36Widget1(),
                    ),
                    Positioned(
                      left: 212.0,
                      top: 364.0,
                      right: null,
                      bottom: null,
                      width: 12.0,
                      height: 3.5,
                      child: GeneratedLine9Widget1(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.04358974358974359;

                        final double height =
                            constraints.maxHeight * 0.020214030915576695;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.06666666666666667,
                              y: constraints.maxHeight * 0.4827586206896552,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child:
                                    GeneratedIconOutlineiconuserremoveWidget1(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.041025641025641026;

                        final double height =
                            constraints.maxHeight * 0.019024970273483946;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.0641025641025641,
                              y: constraints.maxHeight * 0.5410225921521997,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedIconOutlinephoneWidget1(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 27.0,
                      top: 552.0,
                      right: null,
                      bottom: null,
                      width: 15.0,
                      height: 15.0,
                      child: GeneratedIconOutlinecurrencydollarWidget18(),
                    ),
                    Positioned(
                      left: 21.0,
                      top: 499.0,
                      right: null,
                      bottom: null,
                      width: 24.0,
                      height: 24.0,
                      child: GeneratedIconOutlinehomeWidget1(),
                    ),
                    Positioned(
                      left: 21.0,
                      top: 352.0,
                      right: null,
                      bottom: null,
                      width: 24.0,
                      height: 24.0,
                      child: GeneratedIconOutlinecreditcardWidget1(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.06153846153846154;

                        final double height =
                            constraints.maxHeight * 0.028537455410225922;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.05897435897435897,
                              y: constraints.maxHeight * 0.3222354340071344,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedIconOutlinecogWidget1(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.03333333333333333;
                        double scaleX =
                            (constraints.maxWidth * percentWidth) / 13.0;

                        double percentHeight = 0.015457788347205707;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) / 13.0;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.0641025641025641,
                              translateY:
                                  constraints.maxHeight * 0.2080856123662307,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedIconWidget97())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.03076923076923077;
                        double scaleX =
                            (constraints.maxWidth * percentWidth) / 12.0;

                        double percentHeight = 0.0178359096313912;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) / 15.0;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.06666666666666667,
                              translateY:
                                  constraints.maxHeight * 0.267538644470868,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedIconWidget98())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 48.0,
                      top: 163.0,
                      right: null,
                      bottom: null,
                      width: 338.0,
                      height: 417.0,
                      child: GeneratedLoginWidget3(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 43.0,
              child: GeneratedStatusBarWidget14(),
            )
          ]),
    ));
  }
}
