import 'package:flutter/material.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedChoosedecorWidget.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedGroup34Widget.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedAddflowersWidget.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedGroup20Widget2.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedGroup32Widget.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedStatusBarWidget9.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedBouquetWidget.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedToplogoWidget6.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedChooseoptionWidget.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedPickflowersWidget.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedLine4Widget.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedGroup31Widget.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedChooseorderWidget.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedGroup33Widget.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedToplogoWidget5.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedSignupbuttonWidget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedGroup7Widget3.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedFLOWERISTAWidget.dart';
import 'package:flutterapp/floiveryapp/generatedorderfromcompanywidget/generated/GeneratedStatusBarWidget10.dart';

/* Frame Order-from-company
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOrderfromcompanyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 390.0,
              height: 844.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 33.0,
                      top: 57.0,
                      right: null,
                      bottom: null,
                      width: 323.0,
                      height: 50.0,
                      child: GeneratedToplogoWidget5(),
                    ),
                    Positioned(
                      left: 33.0,
                      top: 57.0,
                      right: null,
                      bottom: null,
                      width: 323.0,
                      height: 50.0,
                      child: GeneratedToplogoWidget6(),
                    ),
                    Positioned(
                      left: 136.0,
                      top: 101.0,
                      right: null,
                      bottom: null,
                      width: 131.0,
                      height: 45.0,
                      child: GeneratedFLOWERISTAWidget(),
                    ),
                    Positioned(
                      left: 38.0,
                      top: 141.0,
                      right: null,
                      bottom: null,
                      width: 80.0,
                      height: 34.0,
                      child: GeneratedChooseorderWidget(),
                    ),
                    Positioned(
                      left: 33.0,
                      top: 173.0,
                      right: null,
                      bottom: null,
                      width: 320.0,
                      height: 32.0,
                      child: GeneratedRectangle9Widget(),
                    ),
                    Positioned(
                      left: 59.0,
                      top: 173.0,
                      right: null,
                      bottom: null,
                      width: 97.0,
                      height: 34.0,
                      child: GeneratedPickflowersWidget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.014418458938598633;
                        double scaleX = (constraints.maxWidth * percentWidth) /
                            5.623198986053467;

                        double percentHeight = 0.0090221466046374;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) /
                                7.614691734313965;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.13732597155448717,
                              translateY:
                                  constraints.maxHeight * 0.2237827969953347,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedLine3Widget())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 38.0,
                      top: 211.0,
                      right: null,
                      bottom: null,
                      width: 87.0,
                      height: 34.0,
                      child: GeneratedChooseoptionWidget(),
                    ),
                    Positioned(
                      left: 33.0,
                      top: 243.0,
                      right: null,
                      bottom: null,
                      width: 316.0,
                      height: 33.0,
                      child: GeneratedRectangle10Widget(),
                    ),
                    Positioned(
                      left: 59.0,
                      top: 243.0,
                      right: null,
                      bottom: null,
                      width: 71.0,
                      height: 34.0,
                      child: GeneratedBouquetWidget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.014418458938598633;
                        double scaleX = (constraints.maxWidth * percentWidth) /
                            5.623198986053467;

                        double percentHeight = 0.0090221466046374;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) /
                                7.614691734313965;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.13732597155448717,
                              translateY:
                                  constraints.maxHeight * 0.30672118562092715,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedLine4Widget())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 37.0,
                      top: 356.0,
                      right: null,
                      bottom: null,
                      width: 70.0,
                      height: 34.0,
                      child: GeneratedAddflowersWidget(),
                    ),
                    Positioned(
                      left: 32.0,
                      top: 388.0,
                      right: null,
                      bottom: null,
                      width: 317.0,
                      height: 32.0,
                      child: GeneratedGroup33Widget(),
                    ),
                    Positioned(
                      left: 38.0,
                      top: 290.0,
                      right: null,
                      bottom: null,
                      width: 85.0,
                      height: 26.0,
                      child: GeneratedChoosedecorWidget(),
                    ),
                    Positioned(
                      left: 34.0,
                      top: 314.0,
                      right: null,
                      bottom: null,
                      width: 317.0,
                      height: 32.0,
                      child: GeneratedGroup34Widget(),
                    ),
                    Positioned(
                      left: 137.0,
                      top: 141.0,
                      right: null,
                      bottom: null,
                      width: 115.0,
                      height: 1.0,
                      child: GeneratedLine5Widget(),
                    ),
                    Positioned(
                      left: 137.0,
                      top: 103.0,
                      right: null,
                      bottom: null,
                      width: 115.0,
                      height: 1.0,
                      child: GeneratedLine6Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 445.0,
                      right: null,
                      bottom: null,
                      width: 390.0,
                      height: 120.0,
                      child: GeneratedGroup31Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 573.0,
                      right: null,
                      bottom: null,
                      width: 390.0,
                      height: 120.0,
                      child: GeneratedGroup32Widget(),
                    ),
                    Positioned(
                      left: 39.0,
                      top: 707.0,
                      right: null,
                      bottom: null,
                      width: 315.0,
                      height: 48.0,
                      child: GeneratedSignupbuttonWidget4(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 768.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 76.0,
              child: GeneratedGroup7Widget3(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 43.0,
              child: GeneratedStatusBarWidget9(),
            ),
            Positioned(
              left: 0.0,
              top: 767.9999389648438,
              right: null,
              bottom: null,
              width: 390.0,
              height: 76.00006103515625,
              child: GeneratedGroup20Widget2(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 43.0,
              child: GeneratedStatusBarWidget10(),
            )
          ]),
    ));
  }
}
